# job testing on 
name: check instance id
on:
  push:
    branches:
      - main
jobs:
  identify-runner:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: ech0 "hello world"
        sleep 10
